"""add_indexes

Revision ID: 075adc7f66c4
Revises: cddd8ce3d09a
Create Date: 2026-02-01 22:11:11.050585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '075adc7f66c4'
down_revision: Union[str, Sequence[str], None] = 'cddd8ce3d09a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_emails_external_id_user_email_id', 'emails', ['user_email_id', 'external_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_emails_external_id_user_email_id', 'emails', type_='unique')
    # ### end Alembic commands ###
