"""add_tokens

Revision ID: 45ea4a65b975
Revises: ee37eab68f6d
Create Date: 2026-01-29 14:19:14.607527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45ea4a65b975'
down_revision: Union[str, Sequence[str], None] = 'ee37eab68f6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_emails', sa.Column('access_token', sa.String(), nullable=False))
    op.add_column('user_emails', sa.Column('refresh_token', sa.String(), nullable=True))
    op.add_column('user_emails', sa.Column('expires_at', sa.DateTime(), nullable=False))
    op.add_column('user_emails', sa.Column('obtained_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_emails', 'obtained_at')
    op.drop_column('user_emails', 'expires_at')
    op.drop_column('user_emails', 'refresh_token')
    op.drop_column('user_emails', 'access_token')
    # ### end Alembic commands ###
