"""add_composite_index

Revision ID: 99fb33f9cbb1
Revises: d6a13e901408
Create Date: 2026-02-01 21:50:33.164003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99fb33f9cbb1'
down_revision: Union[str, Sequence[str], None] = 'd6a13e901408'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_emails_user_email_id'), table_name='emails')
    op.create_index('ix_user_external_emails', 'emails', ['user_email_id', 'external_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_external_emails', table_name='emails')
    op.create_index(op.f('ix_emails_user_email_id'), 'emails', ['user_email_id'], unique=False)
    # ### end Alembic commands ###
