"""rename_fields

Revision ID: 9a8d167ee998
Revises: 45ea4a65b975
Create Date: 2026-01-30 13:39:48.524536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9a8d167ee998'
down_revision: Union[str, Sequence[str], None] = '45ea4a65b975'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emails', sa.Column('snippet', sa.String(length=511), nullable=False))
    op.add_column('emails', sa.Column('recieved_at', sa.DateTime(), nullable=False))
    op.drop_column('emails', 'content_snippet')
    op.drop_column('emails', 'received_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emails', sa.Column('received_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('emails', sa.Column('content_snippet', sa.VARCHAR(length=511), autoincrement=False, nullable=False))
    op.drop_column('emails', 'recieved_at')
    op.drop_column('emails', 'snippet')
    # ### end Alembic commands ###
