"""remove_indexes

Revision ID: cddd8ce3d09a
Revises: 99fb33f9cbb1
Create Date: 2026-02-01 22:09:23.867918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cddd8ce3d09a'
down_revision: Union[str, Sequence[str], None] = '99fb33f9cbb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_external_emails'), table_name='emails')
    op.drop_constraint(op.f('uq_emails_external_id_user_email_id'), 'emails', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_emails_external_id_user_email_id'), 'emails', ['external_id', 'user_email_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_user_external_emails'), 'emails', ['user_email_id', 'external_id'], unique=False)
    # ### end Alembic commands ###
