"""unique_constraint_to_email_external_id

Revision ID: d6a13e901408
Revises: 9a8d167ee998
Create Date: 2026-02-01 21:29:43.125950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6a13e901408'
down_revision: Union[str, Sequence[str], None] = '9a8d167ee998'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_emails_external_id_user_email_id', 'emails', ['external_id', 'user_email_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_emails_external_id_user_email_id', 'emails', type_='unique')
    # ### end Alembic commands ###
